# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/prueba/prueba.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==prueba || ORIG_REF_NAME==prueba} -quiet] -quiet

# IP: bd/prueba/ip/prueba_microblaze_riscv_0_0/prueba_microblaze_riscv_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==prueba_microblaze_riscv_0_0 || ORIG_REF_NAME==prueba_microblaze_riscv_0_0} -quiet] -quiet

# IP: bd/prueba/ip/prueba_dlmb_v10_0/prueba_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==prueba_dlmb_v10_0 || ORIG_REF_NAME==prueba_dlmb_v10_0} -quiet] -quiet

# IP: bd/prueba/ip/prueba_ilmb_v10_0/prueba_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==prueba_ilmb_v10_0 || ORIG_REF_NAME==prueba_ilmb_v10_0} -quiet] -quiet

# IP: bd/prueba/ip/prueba_dlmb_bram_if_cntlr_0/prueba_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==prueba_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==prueba_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/prueba/ip/prueba_ilmb_bram_if_cntlr_0/prueba_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==prueba_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==prueba_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/prueba/ip/prueba_lmb_bram_0/prueba_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==prueba_lmb_bram_0 || ORIG_REF_NAME==prueba_lmb_bram_0} -quiet] -quiet

# IP: bd/prueba/ip/prueba_mdm_1_0/prueba_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==prueba_mdm_1_0 || ORIG_REF_NAME==prueba_mdm_1_0} -quiet] -quiet

# IP: bd/prueba/ip/prueba_clk_wiz_1_0/prueba_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==prueba_clk_wiz_1_0 || ORIG_REF_NAME==prueba_clk_wiz_1_0} -quiet] -quiet

# IP: bd/prueba/ip/prueba_rst_clk_wiz_1_100M_0/prueba_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==prueba_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==prueba_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/prueba/ip/prueba_axi_gpio_0_0/prueba_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==prueba_axi_gpio_0_0 || ORIG_REF_NAME==prueba_axi_gpio_0_0} -quiet] -quiet

# IP: bd/prueba/ip/prueba_axi_smc_0/prueba_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==prueba_axi_smc_0 || ORIG_REF_NAME==prueba_axi_smc_0} -quiet] -quiet

# XDC: c:/ultima/project_2/project_2.gen/sources_1/bd/prueba/prueba_ooc.xdc
