# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/ultima/project_2/project_2.runs/synth_1/prueba_wrapper.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param chipscope.maxJobs 3
set_param general.usePosixSpawnForFork 1
set_param bd.open.in_stealth_mode 2
set_msg_config -id {HDL-1065} -limit 10000
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/ultima/project_2/project_2.cache/wt [current_project]
set_property parent.project_path C:/ultima/project_2/project_2.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:nexys-a7-100t:part0:1.3 [current_project]
set_property ip_repo_paths c:/vga_ip/ip_def [current_project]
update_ip_catalog
set_property ip_output_repo c:/ultima/project_2/project_2.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib C:/ultima/project_2/project_2.gen/sources_1/bd/prueba/hdl/prueba_wrapper.v
add_files C:/ultima/project_2/project_2.srcs/sources_1/bd/prueba/prueba.bd
set_property used_in_implementation false [get_files -all c:/ultima/project_2/project_2.gen/sources_1/bd/prueba/ip/prueba_microblaze_riscv_0_0/prueba_microblaze_riscv_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/ultima/project_2/project_2.gen/sources_1/bd/prueba/ip/prueba_microblaze_riscv_0_0/prueba_microblaze_riscv_0_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all c:/ultima/project_2/project_2.gen/sources_1/bd/prueba/ip/prueba_microblaze_riscv_0_0/prueba_microblaze_riscv_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ultima/project_2/project_2.gen/sources_1/bd/prueba/ip/prueba_dlmb_v10_0/prueba_dlmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ultima/project_2/project_2.gen/sources_1/bd/prueba/ip/prueba_ilmb_v10_0/prueba_ilmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ultima/project_2/project_2.gen/sources_1/bd/prueba/ip/prueba_dlmb_bram_if_cntlr_0/prueba_dlmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ultima/project_2/project_2.gen/sources_1/bd/prueba/ip/prueba_ilmb_bram_if_cntlr_0/prueba_ilmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ultima/project_2/project_2.gen/sources_1/bd/prueba/ip/prueba_lmb_bram_0/prueba_lmb_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ultima/project_2/project_2.gen/sources_1/bd/prueba/ip/prueba_mdm_1_0/prueba_mdm_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/ultima/project_2/project_2.gen/sources_1/bd/prueba/ip/prueba_mdm_1_0/prueba_mdm_1_0_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all c:/ultima/project_2/project_2.gen/sources_1/bd/prueba/ip/prueba_clk_wiz_1_0/prueba_clk_wiz_1_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/ultima/project_2/project_2.gen/sources_1/bd/prueba/ip/prueba_clk_wiz_1_0/prueba_clk_wiz_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/ultima/project_2/project_2.gen/sources_1/bd/prueba/ip/prueba_clk_wiz_1_0/prueba_clk_wiz_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ultima/project_2/project_2.gen/sources_1/bd/prueba/ip/prueba_rst_clk_wiz_1_100M_0/prueba_rst_clk_wiz_1_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/ultima/project_2/project_2.gen/sources_1/bd/prueba/ip/prueba_rst_clk_wiz_1_100M_0/prueba_rst_clk_wiz_1_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ultima/project_2/project_2.gen/sources_1/bd/prueba/ip/prueba_axi_gpio_0_0/prueba_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/ultima/project_2/project_2.gen/sources_1/bd/prueba/ip/prueba_axi_gpio_0_0/prueba_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ultima/project_2/project_2.gen/sources_1/bd/prueba/ip/prueba_axi_smc_0/bd_0/ip/ip_1/bd_3e18_psr0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/ultima/project_2/project_2.gen/sources_1/bd/prueba/ip/prueba_axi_smc_0/bd_0/ip/ip_2/bd_3e18_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/ultima/project_2/project_2.gen/sources_1/bd/prueba/ip/prueba_axi_smc_0/bd_0/ip/ip_3/bd_3e18_psr_aclk1_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/ultima/project_2/project_2.gen/sources_1/bd/prueba/ip/prueba_axi_smc_0/bd_0/ip/ip_4/bd_3e18_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ultima/project_2/project_2.gen/sources_1/bd/prueba/ip/prueba_axi_smc_0/bd_0/ip/ip_5/bd_3e18_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ultima/project_2/project_2.gen/sources_1/bd/prueba/ip/prueba_axi_smc_0/bd_0/ip/ip_6/bd_3e18_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ultima/project_2/project_2.gen/sources_1/bd/prueba/ip/prueba_axi_smc_0/bd_0/ip/ip_7/bd_3e18_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ultima/project_2/project_2.gen/sources_1/bd/prueba/ip/prueba_axi_smc_0/bd_0/ip/ip_8/bd_3e18_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ultima/project_2/project_2.gen/sources_1/bd/prueba/ip/prueba_axi_smc_0/bd_0/ip/ip_12/bd_3e18_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ultima/project_2/project_2.gen/sources_1/bd/prueba/ip/prueba_axi_smc_0/bd_0/ip/ip_13/bd_3e18_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ultima/project_2/project_2.gen/sources_1/bd/prueba/ip/prueba_axi_smc_0/bd_0/ip/ip_14/bd_3e18_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ultima/project_2/project_2.gen/sources_1/bd/prueba/ip/prueba_axi_smc_0/bd_0/ip/ip_15/bd_3e18_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ultima/project_2/project_2.gen/sources_1/bd/prueba/ip/prueba_axi_smc_0/bd_0/ip/ip_16/bd_3e18_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ultima/project_2/project_2.gen/sources_1/bd/prueba/ip/prueba_axi_smc_0/bd_0/ip/ip_17/bd_3e18_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ultima/project_2/project_2.gen/sources_1/bd/prueba/ip/prueba_axi_smc_0/bd_0/ip/ip_18/bd_3e18_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ultima/project_2/project_2.gen/sources_1/bd/prueba/ip/prueba_axi_smc_0/bd_0/ip/ip_19/bd_3e18_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ultima/project_2/project_2.gen/sources_1/bd/prueba/ip/prueba_axi_smc_0/bd_0/ip/ip_20/bd_3e18_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ultima/project_2/project_2.gen/sources_1/bd/prueba/ip/prueba_axi_smc_0/bd_0/ip/ip_21/bd_3e18_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ultima/project_2/project_2.gen/sources_1/bd/prueba/ip/prueba_axi_smc_0/bd_0/ip/ip_22/bd_3e18_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ultima/project_2/project_2.gen/sources_1/bd/prueba/ip/prueba_axi_smc_0/bd_0/ip/ip_23/bd_3e18_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ultima/project_2/project_2.gen/sources_1/bd/prueba/ip/prueba_axi_smc_0/bd_0/ip/ip_25/bd_3e18_m01s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ultima/project_2/project_2.gen/sources_1/bd/prueba/ip/prueba_axi_smc_0/bd_0/ip/ip_26/bd_3e18_m01arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ultima/project_2/project_2.gen/sources_1/bd/prueba/ip/prueba_axi_smc_0/bd_0/ip/ip_27/bd_3e18_m01rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ultima/project_2/project_2.gen/sources_1/bd/prueba/ip/prueba_axi_smc_0/bd_0/ip/ip_28/bd_3e18_m01awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ultima/project_2/project_2.gen/sources_1/bd/prueba/ip/prueba_axi_smc_0/bd_0/ip/ip_29/bd_3e18_m01wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ultima/project_2/project_2.gen/sources_1/bd/prueba/ip/prueba_axi_smc_0/bd_0/ip/ip_30/bd_3e18_m01bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ultima/project_2/project_2.gen/sources_1/bd/prueba/ip/prueba_axi_smc_0/bd_0/ip/ip_32/bd_3e18_m02s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ultima/project_2/project_2.gen/sources_1/bd/prueba/ip/prueba_axi_smc_0/bd_0/ip/ip_33/bd_3e18_m02arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ultima/project_2/project_2.gen/sources_1/bd/prueba/ip/prueba_axi_smc_0/bd_0/ip/ip_34/bd_3e18_m02rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ultima/project_2/project_2.gen/sources_1/bd/prueba/ip/prueba_axi_smc_0/bd_0/ip/ip_35/bd_3e18_m02awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ultima/project_2/project_2.gen/sources_1/bd/prueba/ip/prueba_axi_smc_0/bd_0/ip/ip_36/bd_3e18_m02wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ultima/project_2/project_2.gen/sources_1/bd/prueba/ip/prueba_axi_smc_0/bd_0/ip/ip_37/bd_3e18_m02bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ultima/project_2/project_2.gen/sources_1/bd/prueba/ip/prueba_axi_smc_0/ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ultima/project_2/project_2.gen/sources_1/bd/prueba/ip/prueba_axi_smc_0/smartconnect.xdc]
set_property used_in_implementation false [get_files -all c:/ultima/project_2/project_2.gen/sources_1/bd/prueba/ip/prueba_mig_7series_0_1/prueba_mig_7series_0_1/user_design/constraints/prueba_mig_7series_0_1.xdc]
set_property used_in_implementation false [get_files -all c:/ultima/project_2/project_2.gen/sources_1/bd/prueba/ip/prueba_mig_7series_0_1/prueba_mig_7series_0_1/user_design/constraints/prueba_mig_7series_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ultima/project_2/project_2.gen/sources_1/bd/prueba/ip/prueba_mig_7series_0_1/prueba_mig_7series_0_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/ultima/project_2/project_2.gen/sources_1/bd/prueba/ip/prueba_rst_mig_7series_0_81M_0/prueba_rst_mig_7series_0_81M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/ultima/project_2/project_2.gen/sources_1/bd/prueba/ip/prueba_rst_mig_7series_0_81M_0/prueba_rst_mig_7series_0_81M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ultima/project_2/project_2.gen/sources_1/bd/prueba/prueba_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ultima/project_2/project_2.gen/sources_1/bd/prueba/ip/prueba_microblaze_riscv_0_0/data/riscv_bootloop.elf]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/ultima/project_2/project_2.srcs/constrs_1/new/lola.xdc
set_property used_in_implementation false [get_files C:/ultima/project_2/project_2.srcs/constrs_1/new/lola.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental C:/ultima/project_2/project_2.srcs/utils_1/imports/synth_1/prueba_wrapper.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top prueba_wrapper -part xc7a100tcsg324-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef prueba_wrapper.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file prueba_wrapper_utilization_synth.rpt -pb prueba_wrapper_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
